Feature -  Database Migration Service
sourcefuse/terraform-aws-arc-dms pull request #1
Opened 2024-10-21 10:31 UTC by siddharth-singh1

Added module for AWS DMS

2024-10-24 17:24 UTC, siddharth-singh1 commented
Screenshots:
<img width="1069" alt="finished-migration" src="https://github.com/user-attachments/assets/3dd1de67-3c57-4343-b905-5084c2c2c3ab">
<img width="946" alt="pre-commit" src="https://github.com/user-attachments/assets/ec551e40-deab-4c4f-90e2-55e66fb33c62">

2024-10-24 17:28 UTC, vijay-stephen commented
@siddharth-singh1 Please all other files we use in ARC modules like [.github](https://github.com/sourcefuse/terraform-aws-arc-ec2/tree/feature/ec2-alb-module/.github) , [docs/module-usage-guide](https://github.com/sourcefuse/terraform-aws-arc-ec2/tree/feature/ec2-alb-module/docs/module-usage-guide) , [.editorconfig](https://github.com/sourcefuse/terraform-aws-arc-ec2/blob/feature/ec2-alb-module/.editorconfig) etc

2024-10-24 17:34 UTC, tsaucier-sf approved these changes

2024-10-24 17:34 UTC, tsaucier-sf commented on LICENSE
> +   Copyright 2023 SourceFuse
Update to 2024 since this is a new module

2024-10-24 17:34 UTC, tsaucier-sf commented on examples/main.tf
> +    RepoPath = "github.com/terraform-aws-modules"
Update to this repo

2024-10-24 17:36 UTC, tsaucier-sf requested changes

2024-10-24 17:36 UTC, tsaucier-sf commented on examples/main.tf
> +module "aws_dms" {
Use data lookups to find the subnet information from our other ARC modules (network) instead of hardcoding the values in the example.

2024-10-24 18:04 UTC, vijay-stephen requested changes

2024-10-24 18:04 UTC, vijay-stephen commented on examples/main.tf
> +  #s3_endpoints = {}
Remove commented lines if not required

2024-10-24 18:04 UTC, vijay-stephen commented on variables.tf
> +    }))
see if you can add detailed decription to the variables

2024-10-25 14:28 UTC, tsaucier-sf requested changes

2024-10-25 14:28 UTC, tsaucier-sf commented on test/example_test.go
> +	outputValue := terraform.Output(t, terraformOptions, "output_name") // TODO - set the static output variable from example. this needs to be created / set.
You need to update `output_name` with the output from Terraform.

2024-10-25 14:28 UTC, tsaucier-sf commented on test/example_test.go
> +	assert.Equal("output_value", outputValue) // TODO - what is the output value going to be?
Update `output_value` with the value from the output.

2024-10-25 15:07 UTC, vijay-stephen approved these changes

2024-10-25 15:16 UTC, merged